### ISSUE TITLE
Extension continually asks to authenticate

### ISSUE THREAD

**Issue by RichardLitt** [dhatanian/demo-gmail-api#1]
Steps to reproduce:
I've loaded the unpacked extension, and then I click on the browser icon. It asks me to authenticate, and then redirects to my default tab page. After, I go to Gmail, and click on the icon again when looking at an email (which is where I expect this extension to be used, right?). Then, it redirects to the authentication page, again, and asks me to enter my password. On enter, it simply refreshes and asks again. 

Any thoughts? What is the expected behavior?

**Comment by dhatanian** [comment]
Hi Richard, I removed the API project by mistake, which is why Chrome kept asking you to authenticate.

I've fixed this issue. Now it seems the GMail API has slightly changed and the email draft is not created anymore, I'll have a look at it.

**Comment by RichardLitt** [comment]
Thanks; seems to work now. Good to know that the API project needs to be enabled in the Chrome Developers Console in order to stop continually refreshing. 

Cheers!
